name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\NuGet\Cache
            ~\AppData\Local\NuGet\v3-cache
            ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: dotnet --info
        run: dotnet --info

      - name: Restore
        run: dotnet restore src/Game/Game.csproj

      - name: Build
        run: dotnet build src/Game/Game.csproj -c Release --no-restore

      - name: Package Windows build
        shell: pwsh
        run: ./tools/pack-win/pack.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lifeforce-2025-mg-win64
          path: dist/lifeforce-2025-mg-win64.zip
